### ISSUE TITLE
make link klickable

### ISSUE THREAD

**Issue by hansWurst-creator** [resharper-community/resharper-vscode#5]
![image](https://github.com/resharper-community/resharper-vscode/assets/70693364/3c960ba6-092b-4267-b8b8-602cc48e74f5)
Would it be possible to make the link in the problem view clickable? Right now I have to select the link and paste it into a window

**Comment by dev-luckydraw** [comment]
@hansWurst-creator . thanks for your suggestion.
done. the new version is ready in vscode market. 
<img width="503" alt="image" src="https://github.com/resharper-community/resharper-vscode/assets/143685603/267403fb-a019-4185-8b16-ebe8eb235c2e">

**Comment by hansWurst-creator** [comment]
thanks a lot.
